### ISSUE TITLE
Incompatible with Gradle 9.0.

### ISSUE THREAD

**Issue by arduino43** [disk91/helium-etl#1]
Welcome to Gradle 8.5!

Here are the highlights of this release:
 - Support for running on Java 21
 - Faster first use with Kotlin DSL
 - Improved error and warning messages

For more details see https://docs.gradle.org/8.5/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)
> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> error: invalid source release: 21

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

**Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.**

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.5/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD FAILED in 1m
1 actionable task: 1 executed
make: *** [Makefile:7: back] Error 1

**Comment by disk91** [comment]
Solution : Install Java 21
I'll update the (following line)[https://github.com/disk91/helium-etl/blob/46aea92b3cce16a51877b91179105a2951db3cb3/Makefile#L17] with `openjdk-21-jdk`
